# Generated by Django 5.2.5 on 2025-10-13 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_profile',
            name='contact',
            field=models.IntegerField(default='0700000000', max_length = 15),
            preserve_default=False,
        ),
    ]
