# Generated by Django 5.2.5 on 2025-10-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_patient_profile_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_profile',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
