# Generated by Django 5.2.5 on 2025-10-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_alter_patient_profile_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_profile',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
