# Generated by Django 5.2.5 on 2025-10-13 21:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_patientnotes'),
        ('Patient', '0002_patient_profile_contact'),
        ('Pharmacist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_item',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pharmacist.drugs'),
        ),
        migrations.RenameField(
            model_name='doctor_profile',
            old_name='availabiity_schedule',
            new_name='availability_schedule',
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription_item',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prescription_item',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_items', to='Pharmacist.pharmacist_profile'),
        ),
        migrations.AddField(
            model_name='patientnotes',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor_profile'),
        ),
        migrations.AddField(
            model_name='patientnotes',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient_profile'),
        ),
        migrations.DeleteModel(
            name='Drugs',
        ),
    ]
