# Generated by Django 5.2.5 on 2025-10-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill_appointment',
            name='dosage',
            field=models.CharField(default='null'),
        ),
        migrations.AddField(
            model_name='refill_appointment',
            name='duration',
            field=models.CharField(default='null'),
        ),
        migrations.AddField(
            model_name='refill_appointment',
            name='frequency',
            field=models.CharField(default='null'),
        ),
    ]
